# Generated by Django 4.1.4 on 2023-02-28 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_rubricstore_alter_liststore_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Firms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название фирмы')),
            ],
        ),
        migrations.AlterField(
            model_name='liststore',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entry', to='store_app.rubricstore', verbose_name='Рубрика'),
        ),
        migrations.CreateModel(
            name='ChildClothes',
            fields=[
                ('clothes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store_app.clothes')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
            ],
            bases=('store_app.clothes',),
        ),
        migrations.CreateModel(
            name='JoinTheseModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.clothes')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.firms')),
            ],
        ),
        migrations.AddField(
            model_name='firms',
            name='clothes_firms',
            field=models.ManyToManyField(through='store_app.JoinTheseModels', to='store_app.clothes'),
        ),
    ]
